---
version: "2.0"
services:
  earthfast-content-node:
    image: docker.io/earthfast/content-node:v0.6.0
    expose:
      - port: 30080
        as: 80
        to:
          - global: true
        accept:
          - # optional hostname if you want to CNAME a proxy URL to this node
    env:
      - CONTRACT_ADDRESS=0x172CEb125F6C86B7920fD391407aca0B5F416648 # testnet-sepolia
      - DATABASE_DIR=/db_data
      - HOSTING_CACHE_DIR=/hosting_cache
      - HTTP_PORT=30080

      # to be filled in by operator running this node
      - ETH_RPC_ENDPOINT=
      - NODE_ID=
profiles:
  compute:
    earthfast-content-node:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 10Gi
  placement:
    dcloud:
      pricing:
        earthfast-content-node:
          denom: uakt
          amount: 1000
deployment:
  earthfast-content-node:
    dcloud:
      profile: earthfast-content-node
      count: 1
