services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
      - ./nginx-entrypoint.sh:/docker-entrypoint.d/40-config-nginx.sh:ro
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SETUP_SSL=${SETUP_SSL:-false}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${SERVER_NAME}
    depends_on:
      - nginx
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  content-node:
    image: earthfast/content-node:latest
    environment:
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - DATABASE_DIR=/data/database
      - ETH_RPC_ENDPOINT=${RPC_URL}
      - HOSTING_CACHE_DIR=/data/hosting_cache
      - HTTP_PORT=5000
      - NODE_ID=${NODE_ID}
    volumes:
      - ${DATABASE_DIR}:/data/database
      - ${HOSTING_CACHE_DIR}:/data/hosting_cache
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    profiles:
      - autoupdate
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/repo
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_GIT_URL=https://github.com/earthfast/node-operator-tooling
      - WATCHTOWER_GIT_BRANCH=main
      - WATCHTOWER_GIT_PATH=/repo
    command: --interval 60 --cleanup --include-restarting
    restart: unless-stopped

volumes:
  letsencrypt:
