version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SETUP_SSL=${SETUP_SSL:-false}
      - HTTP_PORT=${HTTP_PORT}
    command: >
      /bin/sh -c "
      envsubst '$$SERVER_NAME $$SETUP_SSL $$HTTP_PORT' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf &&
      if [ '${SETUP_SSL}' != 'true' ]; then
        sed -i '/listen 443 ssl/d' /etc/nginx/conf.d/default.conf &&
        sed -i '/ssl_certificate/d' /etc/nginx/conf.d/default.conf;
      fi &&
      nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    entrypoint: /bin/sh
    command: >
      -c '
      if [ "${SETUP_SSL}" = "true" ]; then
        certbot certonly --webroot --webroot-path=/var/www/certbot
        --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email
        -d ${SERVER_NAME} || true;
      else
        echo "SSL setup is disabled";
        sleep infinity;
      fi'
    depends_on:
      - nginx

  content-node:
    image: earthfast/content-node:latest
    environment:
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - DATABASE_DIR=/data/database
      - ETH_RPC_ENDPOINT=${RPC_URL}
      - HOSTING_CACHE_DIR=/data/hosting_cache
      - HTTP_PORT=${HTTP_PORT}
      - NODE_ID=${NODE_ID}
    volumes:
      - ${DATABASE_DIR}:/data/database
      - ${HOSTING_CACHE_DIR}:/data/hosting_cache
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: unless-stopped

volumes:
  letsencrypt:
