services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./http.conf.template:/etc/nginx/templates/http.conf.template:ro
      - ./https.conf.template:/etc/nginx/templates/https.conf.template:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SETUP_SSL=${SETUP_SSL:-false}
    command: >
      /bin/sh -c "
      CLEAN_SERVER_NAME=\$${SERVER_NAME%/};
      export SERVER_NAME=\$CLEAN_SERVER_NAME;
      if [ '${SETUP_SSL}' = 'true' ]; then
        if [ ! -f /etc/letsencrypt/live/\$${SERVER_NAME}/fullchain.pem ]; then
          echo 'SSL certificates not found, starting with HTTP configuration';
          envsubst '$$SERVER_NAME' < /etc/nginx/templates/http.conf.template > /etc/nginx/conf.d/default.conf;
        else
          echo 'SSL certificates found, starting with HTTPS configuration';
          envsubst '$$SERVER_NAME' < /etc/nginx/templates/https.conf.template > /etc/nginx/conf.d/default.conf;
        fi
      else
        echo 'Setting up HTTP configuration for '\$${SERVER_NAME};
        envsubst '$$SERVER_NAME' < /etc/nginx/templates/http.conf.template > /etc/nginx/conf.d/default.conf;
      fi &&
      nginx -g 'daemon off;'"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --force-renewal
      -d ${SERVER_NAME}
    depends_on:
      - nginx
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  content-node:
    image: earthfast/content-node:latest
    environment:
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - DATABASE_DIR=/data/database
      - ETH_RPC_ENDPOINT=${RPC_URL}
      - HOSTING_CACHE_DIR=/data/hosting_cache
      - HTTP_PORT=5000
      - NODE_ID=${NODE_ID}
    volumes:
      - ${DATABASE_DIR}:/data/database
      - ${HOSTING_CACHE_DIR}:/data/hosting_cache
    ports:
      - "5000:5000"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
    restart: unless-stopped

volumes:
  letsencrypt:
