services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    environment:
      - NGINX_HOST=${SERVER_NAME}
      - SETUP_SSL=${SETUP_SSL:-false}
    command: >
      /bin/sh -c "
      echo 'Generating nginx configuration...';
      
      # Remove default config
      rm -f /etc/nginx/conf.d/*.conf
      
      # Write base configuration
      cat > /etc/nginx/conf.d/default.conf << 'EOF'
      server_names_hash_bucket_size 128;

      server {
          listen 80;
          listen [::]:80;
          server_name $NGINX_HOST;
          
          location /.well-known/acme-challenge/ {
              root /var/www/certbot;
          }
      EOF

      if [ '${SETUP_SSL}' = 'true' ]; then
        # Add SSL redirect for HTTP
        cat >> /etc/nginx/conf.d/default.conf << 'EOF'
          
          location / {
              return 301 https://$host$request_uri;
          }
      }

      # Add SSL server block if certificates exist
      if [ -f /etc/letsencrypt/live/$NGINX_HOST/fullchain.pem ]; then
          server {
              listen 443 ssl;
              listen [::]:443 ssl;
              server_name $NGINX_HOST;

              ssl_certificate /etc/letsencrypt/live/$NGINX_HOST/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/$NGINX_HOST/privkey.pem;

              location / {
                  proxy_pass http://content-node:5000;
                  proxy_set_header X-Forwarded-For $remote_addr;
                  proxy_set_header Host $http_host;
              }
          }
      EOF
      else
          echo 'SSL certificates not found, using HTTP only';
      fi
      else
        # Add HTTP proxy if SSL is not enabled
        cat >> /etc/nginx/conf.d/default.conf << 'EOF'
          
          location / {
              proxy_pass http://content-node:5000;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $http_host;
          }
      EOF
      fi

      # Close the first server block
      cat >> /etc/nginx/conf.d/default.conf << 'EOF'
      }
      EOF

      echo 'Final nginx configuration:';
      cat /etc/nginx/conf.d/default.conf;
      
      nginx -g 'daemon off;'"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${SERVER_NAME}
    depends_on:
      - nginx
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  content-node:
    image: earthfast/content-node:latest
    environment:
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - DATABASE_DIR=/data/database
      - ETH_RPC_ENDPOINT=${RPC_URL}
      - HOSTING_CACHE_DIR=/data/hosting_cache
      - HTTP_PORT=5000
      - NODE_ID=${NODE_ID}
    volumes:
      - ${DATABASE_DIR}:/data/database
      - ${HOSTING_CACHE_DIR}:/data/hosting_cache
    ports:
      - "5000:5000"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
    restart: unless-stopped

volumes:
  letsencrypt:
